### ISSUE TITLE
Potentially outdated...?

### ISSUE THREAD

**Issue by AZthemute** [exzork/GCEnkaCopy#3]
The error log should explain it:
![image](https://user-images.githubusercontent.com/104761702/183668360-bedee513-6a61-4f60-8a7d-e6ec8e412059.png)
I couldn't compile this myself - gradle throws tons of errors that... are all like this
![image](https://user-images.githubusercontent.com/104761702/183668680-fa142b64-f27b-48d4-9aad-abf25bb5ec32.png)
Is this project outdated or am I missing something?

**Comment by Julienraptor01** [comment]
i think he compiled it with java 18 or smth and and need smth from it

**Comment by Zhaokugua** [comment]
i think u need to put grasscutter-xxx.jar in lib folder and edit build.gradle as a dependence

**Comment by luckykeeper** [comment]
I tried with java 17 , it works with grasscutter!
![image](https://user-images.githubusercontent.com/34579433/187064815-15f675c6-669c-48e1-abdd-7d963386cf2b.png)

put the grasscutter-xxx.jar in "./libs" folder ,then you can compile it.

However, I also found some problem with the code when compile, here is the error log:
![image](https://user-images.githubusercontent.com/34579433/187064942-a9e7f45b-4b23-43c0-af54-61ec510c8198.png)
After commented this line with "#" ,I get "BUILD SUCCESSFUL"
So I wonder is code has something wrong or I missed something?

OS: Windows Server 2019 DataCenter x64
Java:
openjdk version "17.0.4.1" 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)

**Comment by Julienraptor01** [comment]
Try this (you need to unzip)
[GCEnkaCopy-1.2.jar.zip](https://github.com/exzork/GCEnkaCopy/files/9462386/GCEnkaCopy-1.2.jar.zip)

**Comment by luckykeeper** [comment]
> Try this (you need to unzip) [GCEnkaCopy-1.2.jar.zip](https://github.com/exzork/GCEnkaCopy/files/9462386/GCEnkaCopy-1.2.jar.zip)

It works well with GC 1.2.3-dev-32289e2!
![image](https://user-images.githubusercontent.com/34579433/187830128-91cc86c7-6321-461b-9141-e19506fd493d.png)

**Comment by Julienraptor01** [comment]
> > Try this (you need to unzip) [GCEnkaCopy-1.2.jar.zip](https://github.com/exzork/GCEnkaCopy/files/9462386/GCEnkaCopy-1.2.jar.zip)
> 
> It works well with GC 1.2.3-dev-32289e2!
> ![image](https://user-images.githubusercontent.com/34579433/187830128-91cc86c7-6321-461b-9141-e19506fd493d.png)
> 

It still has multiple problems once you actually use it but it boot fine now

**Comment by exzork** [comment]
fixed with latest release
